apiVersion: v1
kind: Template
metadata:
  name: prometheus-flatliner-image-build-template

objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      namespace: ${NAMESPACE}
      name: ${APPLICATION_NAME}
      labels:
        app: ${APPLICATION_NAME}
    spec:
      dockerImageRepository: ${APPLICATION_NAME}
      tags:
        - name: latest
      lookupPolicy:
        local: true


  - apiVersion: v1
    kind: BuildConfig
    metadata:
      namespace: ${NAMESPACE}
      name: ${APPLICATION_NAME}
      labels:
        app: ${APPLICATION_NAME}
    spec:
      resources:
        limits:
          memory: 1Gi
      output:
        to:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      source:
        git:
          uri: ${GIT_URI}
        type: Git
      strategy:
        type: Source
        sourceStrategy:
          env:
            - name: APP_FILE
              value: 'app.py'
            - name: GIT_SSL_NO_VERIFY
              value: 'true'
            - name: ENABLE_PIPENV
              value: '1'
          forcePull: true
          from:
            kind: DockerImage
            name: 'docker.io/centos/python-36-centos7:latest'
      triggers:
        - imageChange: {}
          type: ImageChange
        - type: ConfigChange

parameters:
  - description: The name of the image
    value: 'prometheus-flatliner'
    name: APPLICATION_NAME
    required: true
  - name: GIT_URI
    value: https://github.com/AICoE/prometheus-flatliner.git
    required: true
  - name: NAMESPACE
    required: true
